### ISSUE TITLE
possible to get obj file for the predicted outputs?

### ISSUE THREAD

**Issue by ghost** [zhuhao-nju/hmd#1]
Is it possible to get obj files for the results predicted and looking for how to use demo outside test images

**Comment by zhuhao-nju** [comment]
By adding "--mesh True" to "python demo.py --ind 2", the obj model will be saved to the result folder.  We are preparing the demo outside test images, which should be uploaded within 3 days.

**Comment by ghost** [comment]
ok thanks looking forward to how to test with my own images
