### ISSUE TITLE
Regrading the training code?

### ISSUE THREAD

**Issue by Naveennavik** [zhuhao-nju/hmd#10]
Hello,
Ur work seems to be great Is there any upadte on the ttraining code ? @zhuhao-nju @zhuhao-nju

**Comment by Naveennavik** [comment]
Can we fit src image of 1080X1080 in the line 231
src_img_l = cv2.resize(src_img, dsize=(448, 448)) in predict_hmd.py

**Comment by zhuhao-nju** [comment]
Hi @Naveennavik , sorry for the late reply.  The training code has been updated in 
src/train_joint.py
src/train_anchor.py
src/train_shading.py

1080x1080 image can be used as input, but it will be cropped and resized to smaller size in the pre-processing.  Also, the subject has to be in the middle of the image.

**Comment by Naveennavik** [comment]
@zhuhao-nju Thanks for giving me the update can you specific the places where u have changed or updated

**Comment by zhuhao-nju** [comment]
@Naveennavik Codes to training the model are added:
src/train_joint.py, src/train_anchor.py, src/train_shading.py
Besides, README.md is updated.
