### ISSUE TITLE
Using an smpl model

### ISSUE THREAD

**Issue by Gogo693** [zhuhao-nju/hmd#12]
Hello, 
I am trying to use an smpl model from smplify instead of hmr for the input and I am trying to understand how to do it. I am using the demo.py and it seems that i need only vertices and vertex normal as input, am I wrong? Because I can't get a solution, especially in the part where you get the silhouette.

**Comment by zhuhao-nju** [comment]
Hi @Gogo693 , sorry for the late reply.  I think what you need is the vertices (or SMPL parameters), and the camera parameters which help render the mesh model to the silhouette.
You may refer to the chapter 3.1 in HMR's paper for the camera parameters,
(http://openaccess.thecvf.com/content_cvpr_2018/papers/Kanazawa_End-to-End_Recovery_of_CVPR_2018_paper.pdf)
or use any other weak-perspective camera model to render the mesh to the silhouette.
