### ISSUE TITLE
Unable to download pretrained model

### ISSUE THREAD

**Issue by khayliang** [zhuhao-nju/hmd#13]
Hello, thank you so much for uploading your code. The link to the pretrained model [here](https://cite.nju.edu.cn/Haozhu/hmd_pretrained_model.tar.gz) seems to be broken. Any idea why?

**Comment by zhuhao-nju** [comment]
Hi @khayliang , sorry for the late reply.  We have transferred the model to Google Drive / Baidu Disk.  Please download from 
https://drive.google.com/file/d/1ImnwfcfuTanjlHbt2t9oe5eZYP3TzDpX/view
or 
https://pan.baidu.com/s/11NpU9NAiO6KOHveWo6tRAg
(extracting code:q23f)
