### ISSUE TITLE
Can HMD produce detailed shape at invisible area?

### ISSUE THREAD

**Issue by mks0601** [zhuhao-nju/hmd#15]
It seems HMD can only produce detailed shape at visible area. Can it produce detailed geometry at invisible area from the image?

**Comment by zhuhao-nju** [comment]
Hi, HMD can only synthesize details at visible area, as ShadingNet requires shading information from the source image.

**Comment by mks0601** [comment]
Got it. Thanks. By the way, how did you get detailed geometry of invisible area at Figure 6 and 7 of the paper?

**Comment by zhuhao-nju** [comment]
> Got it. Thanks. By the way, how did you get detailed geometry of invisible area at Figure 6 and 7 of the paper?

In fact there are no details in the invisible area in Figure 6 and 7.  The invisible area remains unchanged from the anchor-deformed SMPL model.

**Comment by mks0601** [comment]
Great thanks!
