### ISSUE TITLE
Unable to download the pretrained model

### ISSUE THREAD

**Issue by byungyeon89** [zhuhao-nju/hmd#16]
Hello, 

thank you so much for uploading your code. 
The [link](https://drive.google.com/open?id=1ImnwfcfuTanjlHbt2t9oe5eZYP3TzDpX) to the pretrained model here seems to be broken. Any idea why?

**Comment by zhuhao-nju** [comment]
Hi @byungyeon89 , the model can be downloaded from this new link: 
https://drive.google.com/file/d/1LaQBoJPvrqAkF2AGzeV97lmMu9OhsGAS/view?usp=sharing
Thanks for reporting the problem.
