### ISSUE TITLE
Not able to download the pretrained model

### ISSUE THREAD

**Issue by ankitsharma07** [zhuhao-nju/hmd#2]

**Comment by ghost** [comment]
same problem here 
!chmod +x download_pretrained_model.sh
!./download_pretrained_model.sh

Connecting to cite.nju.edu.cn (cite.nju.edu.cn)|114.212.112.6|:80... failed: Connection timed out.
Retrying.

--2019-05-01 16:32:20--  (try: 2)  http://cite.nju.edu.cn/Haozhu/hmd_pretrained_model.tar.gz
Connecting to cite.nju.edu.cn (cite.nju.edu.cn)|114.212.112.6|:80...

**Comment by zhuhao-nju** [comment]
Sorry our server is down by accident, I will inform you when it works.  Furthermore, a google drive link will be added as an alternative.

**Comment by ghost** [comment]
@zhuhao-nju thanks any idea when the server will be back or the link will be added for the google drive?

**Comment by wangsen1312** [comment]
@ak9250   @ankitsharma07  
Hi, we just share a copy of pretrained model on google drive
https://drive.google.com/open?id=1ImnwfcfuTanjlHbt2t9oe5eZYP3TzDpX

**Comment by ankitsharma07** [comment]
@wangsen1312 Thanks
