### ISSUE TITLE
TypeError: preproc_img() got an unexpected keyword argument 'margin'

### ISSUE THREAD

**Issue by ghost** [zhuhao-nju/hmd#3]
I tried to setup the data in wild demo and get this error after setting up hmr
!python ./predict_hmr.py --img ./input/Duncan.jpg --crop_x 100 100
Namespace(crop_x=[100, 100], crop_y=-1, img='./input/Duncan.jpg', outf='./result/Duncan/', pad=0)
Traceback (most recent call last):
  File "./predict_hmr.py", line 48, in <module>
    margin = 30, normalize = True)
TypeError: preproc_img() got an unexpected keyword argument 'margin'

**Comment by zhuhao-nju** [comment]
Problem is solved in the latest commit.  Thanks for reporting.

**Comment by ghost** [comment]
@zhuhao-nju thanks that works now, also i set --gif True but there is no gif result in the results folder
!!python ./predict_hmd.py --img ./input/James.jpg --gif True --mesh True
Namespace(gif=True, gpu=True, img='./input/James.jpg', mesh=True, outf='./result/James/', step=True)
initialize......done
joint deform......done
anchor deform......done
vertex deform......done
render and save......mesh saved to [%s]./result/James/0000_mesh.obj
sh: 1: convert: not found
./input/James.jpg - finished, results are saved to [./result/James/]
hmd done

**Comment by zhuhao-nju** [comment]
@ak9250 I think "sudo  apt-get install imagemagick" should solve it, as the missing "convert" is from ImageMagic.

**Comment by ghost** [comment]
@zhuhao-nju yes that solved it thanks
