### ISSUE TITLE
Training

### ISSUE THREAD

**Issue by jsaisagar** [zhuhao-nju/hmd#5]
Hi, 

Thanks for sharing the code.

May I know how could we train the model i.e. could you provide training file?

Thanks

**Comment by zhuhao-nju** [comment]
Hi @jsaisagar , we plan to add the training code but it may take a while.  Please leave this issue open and we will let you know when the training code is uploaded.

**Comment by xiaoiker** [comment]
Appreciate your great work and Look forward to the training part.

**Comment by gh18l** [comment]
Even can't wait to release!

**Comment by liwenssss** [comment]
great job!
I am reading the paper recently and I cannot wait to learn the code to learn more about the paper. If u can upload it recently, I cannot be more appreciate it! 
By the way, are u feel it ok to have a conversation private about the job? I have some questions about the paper.
THX!!~~~

**Comment by zszclever** [comment]
Thank you for your hard work. Great job!
when I run the command "python eval_recon.py --tgt hmr"， it seems that the procedure missing "eval_function".
![image](https://user-images.githubusercontent.com/46366003/65692688-8f4e2680-e0a5-11e9-857a-4c9113ca3c25.png)
So which file do I need when I run eval_recon.py?

**Comment by zhuhao-nju** [comment]
> Thank you for your hard work. Great job!
> when I run the command "python eval_recon.py --tgt hmr"， it seems that the procedure missing "eval_function".
> ![image](https://user-images.githubusercontent.com/46366003/65692688-8f4e2680-e0a5-11e9-857a-4c9113ca3c25.png)
> So which file do I need when I run eval_recon.py?

Thanks for the report, the latest commit fixes this problem, or you could just rename eval_tools.py to eval_functions.py to solve it.

**Comment by zszclever** [comment]
Thank you very much for your help!!!

**Comment by Taye310** [comment]
looking forward to the shading-net train code, best regards.
