### ISSUE TITLE
Pretrained model file inaccessible

### ISSUE THREAD

**Issue by t-suzuki** [zhuhao-nju/hmd#8]
Hello, thank you for sharing the great work!

I've found that URL for the pretrained model (http://cite.nju.edu.cn/Haozhu/hmd_pretrained_model.tar.gz) in https://github.com/zhuhao-nju/hmd/blob/master/demo/download_pretrained_model.sh is no longer accessible and it is redirected to the top page of your lab.

FYI: also, [Project Page] link in the README.md is outdated.

It would be great if you could give us a new URL for the pretrained model.
Thanks in advance.

**Comment by wangsen1312** [comment]
Sorry our server is down by accident, I will inform you when it works.  We just share a copy of pretrained model on google drive
https://drive.google.com/open?id=1ImnwfcfuTanjlHbt2t9oe5eZYP3TzDpX

**Comment by t-suzuki** [comment]
Thank you! successfully downloaded.
