### ISSUE TITLE
How could I get the .json file 

### ISSUE THREAD

**Issue by youwei-kafuu** [zhuhao-nju/hmd#9]
Hi,
I want to test my own data,but I'm wondering how can I get the .json file in the "/test/para" folder?I seem to not find the approach to get the .json file through HMR.

Thanks

**Comment by zhuhao-nju** [comment]
Hi, 
You may find the approach to test your images here: https://github.com/zhuhao-nju/hmd/blob/master/demo_wild/demo_wild.md
The json file is not needed in the above-mentioned demo as it contains the HMR predicting part.
